# dbt_project.yml
name: 'p1'
version: '1.0.0'
config-version: 2

profile: 'airlines'

# Define where models are stored
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"] 
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Optional: Define how models are materialized (table/view)
# models:
#   p1:
#     +materialized: view